name: Immersive Railroading Build Pipeline

on: [push]

jobs:
  forge_1-7-10:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt install -y pngquant findutils
    - name: Process images
      run: find src/main/resources/assets/immersiverailroading/ | grep png | xargs -I foo pngquant -s1 -f --ext .png foo
    - name: Setup Universal Mod Core (and helpers)
      run: ./setup.sh forge_1.7.10 useHttps
    - name: Gradle build
      run: ./gradlew build
    - uses: actions/upload-artifact@master
      with:
        name: Immersive Railroading 1.7.10
        path: build/libs/ImmersiveRailroading-1.7.3_1.7.10.jar

  forge_1-10-2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt install -y pngquant findutils
    - name: Process images
      run: find src/main/resources/assets/immersiverailroading/ | grep png | xargs -I foo pngquant -s1 -f --ext .png foo
    - name: Setup Universal Mod Core (and helpers)
      run: ./setup.sh forge_1.10.2 useHttps
    - name: Gradle build
      run: ./gradlew build
    - uses: actions/upload-artifact@master
      with:
        name: Immersive Railroading 1.10.2
        path: build/libs/ImmersiveRailroading-1.7.3_1.10.2.jar

  forge_1-11-2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt install -y pngquant findutils
    - name: Process images
      run: find src/main/resources/assets/immersiverailroading/ | grep png | xargs -I foo pngquant -s1 -f --ext .png foo
    - name: Setup Universal Mod Core (and helpers)
      run: ./setup.sh forge_1.11.2 useHttps
    - name: Gradle build
      run: ./gradlew build
    - uses: actions/upload-artifact@master
      with:
        name: Immersive Railroading 1.11.2
        path: build/libs/ImmersiveRailroading-1.7.3_1.11.2.jar

  forge_1-12-2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt install -y pngquant findutils
    - name: Process images
      run: find src/main/resources/assets/immersiverailroading/ | grep png | xargs -I foo pngquant -s1 -f --ext .png foo
    - name: Setup Universal Mod Core (and helpers)
      run: ./setup.sh forge_1.12.2 useHttps
    - name: Gradle build
      run: ./gradlew build
    - uses: actions/upload-artifact@master
      with:
        name: Immersive Railroading 1.12.2
        path: build/libs/ImmersiveRailroading-1.7.3_1.12.2.jar

  forge_1-14-4:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt install -y pngquant findutils
    - name: Process images
      run: find src/main/resources/assets/immersiverailroading/ | grep png | xargs -I foo pngquant -s1 -f --ext .png foo
    - name: Setup Universal Mod Core (and helpers)
      run: ./setup.sh forge_1.14.4 useHttps
    - name: Gradle build
      run: ./gradlew build
    - uses: actions/upload-artifact@master
      with:
        name: Immersive Railroading 1.14.4
        path: build/libs/ImmersiveRailroading-1.7.3_1.14.4.jar

  fabric_1-14-4:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt install -y pngquant findutils
    - name: Process images
      run: find src/main/resources/assets/immersiverailroading/ | grep png | xargs -I foo pngquant -s1 -f --ext .png foo
    - name: Setup Universal Mod Core (and helpers)
      run: ./setup.sh fabric_1.14.4 useHttps
    - name: Gradle build
      run: ./gradlew build
    - uses: actions/upload-artifact@master
      with:
        name: Immersive Railroading 1.14.4
        path: build/libs/ImmersiveRailroading-1.7.3_fabric_1.14.4.jar

  fabric_1-15-2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt install -y pngquant findutils
    - name: Process images
      run: find src/main/resources/assets/immersiverailroading/ | grep png | xargs -I foo pngquant -s1 -f --ext .png foo
    - name: Setup Universal Mod Core (and helpers)
      run: ./setup.sh fabric_1.15.2 useHttps
    - name: Gradle build
      run: ./gradlew build
    - uses: actions/upload-artifact@master
      with:
        name: Immersive Railroading 1.15.2
        path: build/libs/ImmersiveRailroading-1.7.3_fabric_1.15.2.jar
