name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install deps
      run: sudo apt install -y pngquant xargs
    - name: Process images
      run: find src/main/resources/assets/immersiverailroading/ | grep png | xargs -I foo pngquant -s1 -f --ext .png foo
    - name: Setup Universal Mod Core (and helpers)
      run: ./setup.sh forge_1.12.2 useHttps
    - name: Gradle build
      run: ./gradlew build
    - uses: actions/upload-artifact@master
      with:
        name: Immersive Railroading 1.12.2
        path: build/libs/ImmersiveRailroading-1.7.1_1.12.2.jar
